# Generated by Django 5.1.6 on 2025-03-01 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vectordb',
            fields=[
                ('id_vector', models.AutoField(primary_key=True, serialize=False)),
                ('index_faiss', models.FileField(upload_to='')),
                ('index_pkl', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('nom_chat', models.CharField(max_length=50)),
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('id_vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.vectordb')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('reponse', models.CharField(max_length=510)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=50)),
                ('id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
            ],
        ),
    ]
