# Generated by Django 5.1.6 on 2025-03-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_vectordb_id_chat_alter_vectordb_index_faiss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vectordb',
            name='id_chat',
        ),
    ]
