# Generated by Django 5.1.6 on 2025-03-02 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_vectordb_id_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectordb',
            name='id_chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vectordb', to='chat.chat'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id_vector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.vectordb'),
        ),
    ]
