# Generated by Django 5.1.6 on 2025-03-02 20:02

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chat_id_vector_chat_index_faiss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='index_faiss',
            field=models.FileField(upload_to=chat.models.get_vectordb_upload_path),
        ),
        migrations.AlterField(
            model_name='chat',
            name='index_pkl',
            field=models.FileField(upload_to=chat.models.get_vectordb_upload_path),
        ),
    ]
